defaults:
  - MaskRCNN
hydra:
  run:
    dir: "logs/${hydra:job.config_name}/${now:%Y-%m-%d_%H-%M-%S}"
program:
  random_seed: 42
  search_optimum_learning_rate: false
logging:
  wandb:
    use: true
    project_name: ParticleMixtureAnalysis
callbacks:
  early_stopping:
    monitor: validation/mAP
    patience: 20
    mode: max
  model_checkpoint:
    monitor: validation/mAP
    mode: max
    filename: '{epoch}-{step}-{validation/mAP:.4f}'
  example_detection_monitor:
    score_threshold: 0.5
    do_display_box: false
    do_display_label: true
    do_display_score: true
    do_display_mask: true
    do_display_outlines_only: true
    line_width: 1
    font_size: 16
trainer:
  fast_dev_run: false
  max_epochs: 300
  log_gpu_memory: false
  gpus: -1
lightning_module:
  learning_rate: 0.005
  drop_lr_on_plateau_patience: 10
  num_classes: 3
  model_kwargs:
    box_detections_per_img: 400
data_module:
  data_root: data/complete
  batch_size: 2
  train_subset: training_synthetic_circular
  val_subset: validation_synthetic_circular
  initial_cropping_rectangle: null
  random_cropping_size: null
  class_selector: null
  num_samples_limit_train: 400
  user_albumentation_train:
    __version__: null
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      additional_targets: {}
      bbox_params: null
      keypoint_params: null
      p: 1.0
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.VerticalFlip
        always_apply: false
        p: 0.5
